name: '${name}'
version: ${version}
main: ron.thewizard.roleplayextras.RoleplayExtras
authors: [ xGinko ]
description: '${description}'
website: '${url}'
api-version: '1.20'
folia-supported: true
soft-depend:
  - voicechat

commands:
  roleplayextras:
    usage: /roleplayextras [ reload, version ]
    description: RoleplayExtras admin commands
    aliases:
      - rpextras
  walkspeed:
    usage: /walkspeed <speed> (player)
    description: Sets walking speed
  voicepitch:
    usage: /voicepitch <pitch> (player)
    description: Sets voice pitch