name: '${name}'
version: ${version}
main: ron.thewizard.roleplayextras.RoleplayExtras
authors: [ xGinko ]
description: '${description}'
website: '${url}'
api-version: '1.21'
folia-supported: true
softdepend:
  - packetevents
  - Citizens

commands:
  roleplayextras:
    usage: /roleplayextras [ reload, version ]
    description: RoleplayExtras admin commands
    aliases:
      - rpextras
  walkspeed:
    usage: /walkspeed <speed> (player)
    description: Sets walking speed